on:
  push:
    tags: ['*']

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: apt-update
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get update

      - name: autoremove
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt autoremove

      - name: Install libarchive rpm on Linux
        if: startsWith(matrix.os, 'ubuntu-latest')
        run: sudo apt-get install libarchive-tools rpm

      - name: Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Archive win-unpacked folder
        if: startsWith(matrix.os, 'windows-latest')
        run: |
          mkdir -p build/win-unpacked
          cp -r dist/win-unpacked/* build/win-unpacked/
          tar -czvf win-unpacked.tar.gz -C build win-unpacked

      - name: Upload win-unpacked artifact
        if: startsWith(matrix.os, 'windows-latest')
        uses: actions/upload-artifact@v3
        with:
          name: win-unpacked
          path: win-unpacked.tar.gz
